name: "Test 이슈 생성"
description: "Test Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다."
title: "이슈 이름을 작성해주세요."
labels: [order]

body:
  - type: input
    id: parent_key # ← snake_case 권장
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요."
      placeholder: "TS-123"
    validations:
      required: true

  - type: input
    id: branch_name
    attributes:
      label: "브랜치 이름 (이슈 요약)"
      description: "영문 소문자로 브랜치 이름을 지어주세요. (ex: domain-feature)"
    validations:
      required: true

  - type: input
    id: branch_prefix
    attributes:
      label: "브랜치 전략(GitFlow)"
      description: "feat/fix/docs/style/refactor/test/chore 중 해당 이슈와 걸맞게 작성해주세요."
    validations:
      required: true

  - type: textarea
    id: details_md # 내용은 마크다운으로 받도록 명시
    attributes:
      label: "상세 내용(Details)"
      description: "이슈 내용을 자세히 설명해주세요. (Markdown 가능)"
      value: |
        - 상세 내용에 대해 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: tasks_md
    attributes:
      label: "체크리스트(Tasks)"
      description: "해당 이슈에 대해 필요한 작업 목록을 작성해주세요. (Markdown 체크박스 사용 가능)"
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
